name: payments

on: 
    push:
        paths:
            - 'payments/**'
        branches:
            - main
    pull_request:
        paths:
            - 'payments/**'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/cache@v5
              with:
                path: ~/.npm
                key: payments-${{ hashFiles('payments/package-lock.json') }}
            - run: cd payments && npm install && npm run test:ci
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - run: cd payments && docker build --cache-from apkwan/ticket-payments:latest -t apkwan/ticket-payments .
            - uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push apkwan/ticket-payments