name: tests-payments

on: 
    push:
        paths:
            - 'payments/**'
    pull_request:
        paths:
            - 'payments/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - run: cd payments && npm install && npm run test:ci
